### PR TITLE
Fixes invalid links on the home page

### LINKED ISSUE #173: Fix invalid links for new blog articles on homepage
e.g. instead of `ieee.nitk.ac.in/blog//coronary-stents/`, the links direct to `https://ieee.nitk.ac.in/p://ieee.nitk.ac.in/blog//coronary-stents/`

### PR DESCRIPTION
**Pull request by mahim23**
Resolves #173 

### Description
Since the `search.json` file has hardcoded links, the [articleHref](https://github.com/IEEE-NITK/ieee-nitk.github.io/blob/master/js/cta.js#L77) variable had the incorrectly sliced string as the links were changed from `ieeenitk.org` to `ieee.nitk.ac.in`.

### CODE REVIEW

File: js/cta.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ function renderArticle(article, section, number) {
     article.tags = processTags(article.tags);
     var sectionSelector = "#article" + number;
 
-    var articleHref = "./" + article.url.slice(article.url.indexOf("org") + 4);
+    var articleHref = "./" + article.url.slice(article.url.indexOf("in") + 3);
```
Comment (pvgupta24) [inline js/cta.js]:
```suggestion
    var articleHref = "./" + article.url.slice(article.url.indexOf(".in") + 4);
```
Looks fine as a temporary fix.
Lets slice from ".in" to prevent other "in" which may occur as a substring. @mahim23  WDYT?
